# -*- coding: utf-8 -*-
"""StudentPerformance_Visualizationipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t2sth6CpU1ADwWyAEPD8Goxc3or8eE4Q

#Uploading Cleaned Dataset
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import files
uploaded = files.upload()

"""#Loading and Displaying the Contents"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture result_output_1
# import pandas as pd
# 
# # Loading the dataset
# df = pd.read_csv('clean_studentsperformance_data.csv')
# 
# # Displaying the dataset
# print(df)
#

"""#Data Visualization"""

sns.set(style="whitegrid")

# 1. Bar Plot - Comparing average scores by gender
plt.figure(figsize=(5, 5))
sns.barplot(x='gender', y='math score', data=df, ci=None, color='skyblue')
plt.title('Average Math Score by Gender')
plt.ylabel('Average Math Score')
plt.xlabel('Gender')
plt.show()

# 2. Box Plot - Distribution of scores in Math, Reading, and Writing
plt.figure(figsize=(10, 6))
sns.boxplot(data=df[['math score', 'reading score', 'writing score']])
plt.title('Score Distribution for Math, Reading, and Writing')
plt.ylabel('Scores')
plt.show()

# 3. Scatter Plot - Math vs Reading Scores
plt.figure(figsize=(8, 6))
sns.scatterplot(x='math score', y='reading score', hue='gender', data=df)
plt.title('Math vs Reading Scores')
plt.xlabel('Math Score')
plt.ylabel('Reading Score')
plt.show()

# 4. Histogram - Distribution of Math Scores
plt.figure(figsize=(8, 6))
sns.histplot(df['math score'], bins=20, kde=True, color='green')
plt.title('Distribution of Math Scores')
plt.xlabel('Math Score')
plt.ylabel('Frequency')
plt.show()

# 5. Correlation Heatmap - Correlation between Math, Reading, and Writing Scores
plt.figure(figsize=(8, 6))
correlation = df[['math score', 'reading score', 'writing score']].corr()
sns.heatmap(correlation, annot=True, cmap='coolwarm', linewidths=0.5)
plt.title('Correlation between Math, Reading, and Writing Scores')
plt.show()

"""#Capturing Results into a Text File"""

with open('studentperformance_dataanalysis_result.txt', 'w') as f:

    f.write(result_output_1.stdout + '\n')

from google.colab import files
files.download('studentperformance_dataanalysis_result.txt')