# -*- coding: utf-8 -*-
"""DataAnalysis_SourceCodeipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17uPFKZ9wHkL5AGNKZHg2JlDP7LQcH5Jn

#Uploading Cleaned CSV File
"""

from google.colab import files

uploaded = files.upload()

"""#Loading and Displaying File Contents"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture result_output_1
# import pandas as pd
# 
# 
# # Loading the CSV file
# df = pd.read_csv('clean_frailty_data_1.csv')
# 
# # Displaying the contents
# print(df)
# 
# 
# 
#

"""#Data Visualization


"""

import seaborn as sns
import matplotlib.pyplot as plt

# Box plot
sns.boxplot(x='Frailty', y='Grip_strength', data=df)
plt.title('Grip Strength by Frailty Status')
plt.xlabel('Frailty Status')
plt.ylabel('Grip Strength')
plt.show()

"""#Performing Two Sample T-Test"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture result_output_2
# import numpy as np
# from scipy import stats
# 
# grip_strength_non_frail = np.array([30, 31, 29, 26, 19, 31])
# grip_strength_frail = np.array([28, 24, 22, 20])
# 
# # Performing a two-sample t-test
# t_stat, p_value = stats.ttest_ind(grip_strength_non_frail, grip_strength_frail)
# 
# 
# print(f"T-statistic: {t_stat}")
# print(f"P-value: {p_value}")
# 
# alpha = 0.05
# if p_value < alpha:
#     print("Reject the null hypothesis: There is a significant difference in grip strength between frail and non-frail participants.")
# else:
#     print("Fail to reject the null hypothesis: There is no significant difference in grip strength between frail and non-frail participants.")
#

"""#Capturing Results into a Text File

"""

with open('dataanalysis_result.txt', 'w') as f:

    f.write(result_output_1.stdout + '\n')
    f.write(result_output_2.stdout + '\n')

from google.colab import files
files.download('dataanalysis_result.txt')